name: CI Checks

on:
  push:
    paths:
      - "expo-boomboomapp/**"
      - .github/workflows/checks.yml
  pull_request:

defaults:
  run:
    working-directory: expo-boomboomapp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./package-lock.json
      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Check Formatting
        run: npm run format-check

      - name: Check Ts
        run: npm run ts-check
